services:
    kmfk.hateoas.serialization_event_listener:
        class: Kmfk\Bundle\HateoasBundle\EventListener\SerializationListener
        arguments:
            - @request
            - @annotation_reader
            - %kmfk.hateoas%
        scope: request
        tags: 
            - { name: jms_serializer.event_subscriber }
